name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      API_HOST: ${{ secrets.API_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.6.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist